
CONFIG_UART_CONSOLE=y



CONFIG_LOG=y
#interrupts  
#CONFIG_IRQ=y 
CONFIG_GPIO=y
CONFIG_SHARED_INTERRUPTS=n

#enabling non secure GPIOTE driver for nrf91
CONFIG_TRUSTED_EXECUTION_NONSECURE=y



CONFIG_CPP=y

# GPIO register backend owns GPIOTE; keep the GPIO driver from claiming its IRQ.
CONFIG_GPIO_NRFX_INTERRUPT=n


#debug 
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4